Routinetask 엔티티 추가, Routine CRUD에 적용
depromeet/imgoing-backend pull request #35
Opened 2021-10-22 14:52 UTC by ybell1028

# 북마크된 준비항목을 그루핑할 수 있는 Routine 기능
- Routine과 Task를 M:N으로 맺어주기 위한 Routinetask 엔티티 추가
- 표시 순서 priority 컬럼 추가
- 기존 List 형식의 속성 이름 복수형으로 변경
- **루틴 등록시 준비항목의 북마크 여부 검사** 로직 추가
- DB와의 통신 횟수를 줄이기위해 루틴 수정 알고리즘을 짰는데 생각보다 너무 길어진 느낌 **(이부분 꼼꼼히 리뷰 부탁!)**

2021-10-23 05:26 UTC, bluayer requested changes
전체적으로 Controller에 있는 로직들을 Service 쪽으로 옮겨야 할꺼 같아!
Controller는 일반적으로 사용자한테 Input 받아서 Output을 만들어서 반환해주는 곳이라고 생각되는 거 같아.
Service의 의미를 한 번 생각해보고, 지금 방식이 절차지향적이지 않은지도 고려해보자!

2021-10-23 05:26 UTC, bluayer commented on src/main/java/org/imgoing/api/controller/RoutineController.java
> +        routinetaskService.saveAll(newRoutine.getRoutinetasks());
유진이 PR에도 남겼지만 이 부분들이 Controller에 있는게 맞을까?
관계를 설정해주고, Repository를 거치는 부분이 Controller에도 있게 되면 서비스의 존재 의의가 어떤걸까?
이 부분 한 번 생각해보기!

2021-10-23 05:26 UTC, bluayer commented on src/main/java/org/imgoing/api/repository/RoutineRepository.java
> +    @Query(value = "SELECT * FROM routine_tb WHERE routine_tb.user_id = :userId", nativeQuery = true)
Q1. JPQL을 사용하지 않은 이유? Native Query가 더 이해하기 쉽다고 생각해서 이렇게 작성한건가?
Q2. findAllbyUserId를 하면 위하고 같은 형식의 쿼리가 아니라 추가적인 쿼리가 날아가서 쿼리를 따로 작성한건가?

2021-10-23 05:26 UTC, bluayer commented on src/main/java/org/imgoing/api/service/PlantaskService.java
> +                .orElseThrow(() -> new ImgoingException(ImgoingError.BAD_REQUEST, "존재하지 않는 루틴입니다."));
User가 접근 가능한 PlanTask인지 확인해주면 좋을 듯!

2021-10-23 05:26 UTC, bluayer commented on src/main/java/org/imgoing/api/domain/entity/Routinetask.java
> +    }
compareTo 구현한 이유가 어떤거야?

2021-10-23 09:55 UTC, ybell1028 commented on src/main/java/org/imgoing/api/repository/RoutineRepository.java
> +    @Query(value = "SELECT * FROM routine_tb WHERE routine_tb.user_id = :userId", nativeQuery = true)
초기 테스트할때 예전 코드에서 쓰던걸 가져온게 있는데 깜빡하고 안고쳤나봐 JPQL로 변경할께

2021-10-23 09:56 UTC, ybell1028 commented on src/main/java/org/imgoing/api/service/PlantaskService.java
> +                .orElseThrow(() -> new ImgoingException(ImgoingError.BAD_REQUEST, "존재하지 않는 루틴입니다."));
Plantask는 유진이 파트라 합치고 난다음 수정하면 될꺼같아

2021-10-23 09:58 UTC, ybell1028 commented on src/main/java/org/imgoing/api/domain/entity/Routinetask.java
> +    }
getRoutinetask()할 때 priorty 순으로 정렬하기 위해서 Collection.sort를 사용하거든
그래서 구현해놨어ㅋㅋ

2021-10-25 00:26 UTC, bluayer approved these changes
Push Test를 위한 Approve!

2021-10-25 12:38 UTC, bluayer approved these changes
일반적으로 엔티티 조회, 수정, 삭제 관련해서는 User에게 해당 엔티티를 RUD할 수 있는 권한이 있는지 확인해야 하긴 하는데, 일단 기간이 급하니깐 Apporve!

2021-10-25 13:34 UTC, merged