Plan CRUD 로직 수정
depromeet/imgoing-backend pull request #36
Opened 2021-10-22 18:02 UTC by ujin2021

- Plan 조회 시 포함된 Task도 함께 조회
- Plan 생성/수정/삭제 시 Task, PlanTask도 함께 생성/수정/삭제
- 코드 구현이 효율적인지, 개선할 부분 있는지 리뷰부탁드려요

2021-10-23 03:42 UTC, ybell1028 requested changes

2021-10-23 03:42 UTC, ybell1028 commented on src/main/java/org/imgoing/api/controller/PlanController.java
> +            @ApiResponse(code = 201, message = "일정 생성 성공", response = PlanDto.class),
이런 어노테이션이 있었다니... 나중에 나도 써봐야겠다!

2021-10-23 03:42 UTC, ybell1028 commented on src/main/java/org/imgoing/api/domain/entity/Plan.java
> +}
@setter로 setter 메소드가 이미 있을껀데 setUser()를 사용해주면 되지 않을까?

2021-10-23 03:42 UTC, ybell1028 commented on src/main/java/org/imgoing/api/controller/PlanController.java
> +        }
```java
List<PlanDto> planDtos = planService.getPlans(user.getId()).stream()
		.map(plan - > planMapper.toDto(plan, plan.getTaskList()))
		.collect(Collectors.toList());
```
for문을 보면 스트림으로 고치고 싶어지는 병에 걸린 나

2021-10-23 03:42 UTC, ybell1028 commented on src/main/java/org/imgoing/api/controller/PlanController.java
> +        }
이 부분도 반복문이 돌면서 Task가 하나씩 DB에 삽입 되는데
```java
	List<Task> saveList = taskDtos.stream()
		.filter(taskDto -> !taskDto.getIdBookmarked())
		.map(taskMapper::toEntity)
		.collection(Collectors.toList())
```
이렇게 insert할 task만 필터링해서 saveAll()로 한번에 삽입하는게 좋을꺼같아

2021-10-23 03:42 UTC, ybell1028 commented on src/main/java/org/imgoing/api/domain/entity/Plan.java
> +    @OneToMany(mappedBy = "plan", cascade = CascadeType.REMOVE, fetch = FetchType.EAGER)
CascadeType.REMOVE인 경우 고아객체가 삭제되지 않는데, Plan이 삭제되면 Plan과 관련된 Plantask도 삭제되어야 하는게 아닐까?

2021-10-23 03:42 UTC, ybell1028 commented on src/main/java/org/imgoing/api/controller/PlanController.java
> +        planService.deleteTask(plan);
나도 비슷하게 기존 task와 plantask를 전부 삭제하고 전부 새로 추가하는 로직을 맨처음 생각했는데 이런 단점이 떠올랐어
- **쓸데없는 삽입 삭제 연산 수가 늘어난다.**
- **사용할 수록 실제 데이터 수에 비해 PK가 엄청나게 증가**할 것 같아서 장기적으로 좋지 않다

따라서 기존에 이미 저장되어 있던 데이터는 남겨두고
1. 필요없는(Dto에 들어있지 않은) 데이터만 골라서 삭제
2. 새로 생성해야할(List<Plantasks>에는 없으나, Dto에 들어있는) 데이터만 골라서 생성
3. 결과값을 Dto로 매핑하여 응답

대충 이런 로직으로 수정 기능을 만들려고 노력했어!

2021-10-23 03:42 UTC, ybell1028 commented on src/main/java/org/imgoing/api/service/PlanService.java
>      }
갈아 엎느라 수고 많았어... 😢

2021-10-23 05:01 UTC, bluayer commented on src/main/java/org/imgoing/api/domain/entity/Plan.java
> +}
@ujin2021 @ybell1028 
엔티티에 Setter가 있는 게 정말 좋은 일일까?
이 부분도 한 번 둘 다 고민해보기!

2021-10-23 05:13 UTC, bluayer requested changes
이미 리뷰 내용이 적절해보여서 나는 도메인적인 측면만 좀 다뤘어~

2021-10-23 05:13 UTC, bluayer commented on src/main/java/org/imgoing/api/controller/PlanController.java
> +        plantaskService.saveAll(plan.getPlantasks());
이 부분이 Controller에 있는게 정말 맞을까?
Controller는 일반적으로 사용자에게 입력을 받고 Output을 만들어서 주는 역할을 담당하는 곳이야.
유진이가 작성한 이 부분은 비즈니스 로직에 가까운거 같은데 어떻게 생각해?

2021-10-23 05:13 UTC, bluayer commented on src/main/java/org/imgoing/api/controller/PlanController.java
> +    public ImgoingResponse<PlanDto> update (User user, @RequestBody @Valid PlanDto planDto) {
여기도 같은 맥락으로 Controller에 있어야 하는 로직이 아니지 않을까?
특히 @Transactional의 이점도 못 누리고!

2021-10-23 05:13 UTC, bluayer commented on src/main/java/org/imgoing/api/domain/entity/Plan.java
> +    public void setPlantask(List<Task> tasks) {
setPlantask로 이름을 지으면 엄청 편리하겠지만,
만약 제 3자가 와서 우리 시스템을 봤을 때 Plantask가 뭐지?부터 생각하게 될꺼야.
도메인적으로 `registerPlantask`라던지, `registerTasksForReady` 같은 이름을 써주는게 더 명확하지 않을까?
"준비 항목을 등록한다"의 기능을 하는 함수가 드러났으면 좋을 것 같아!

2021-10-23 05:13 UTC, bluayer commented on src/main/java/org/imgoing/api/controller/PlanController.java
> +        plan.addUser(user);
addUser도 Service 내부에서 사용해야 합리적이겠지?

2021-10-23 06:19 UTC, ujin2021 commented on src/main/java/org/imgoing/api/controller/PlanController.java
> +            @ApiResponse(code = 201, message = "일정 생성 성공", response = PlanDto.class),
응응 swagger 응답 설명 추가하는 어노테이션이야

2021-10-23 06:48 UTC, ujin2021 commented on src/main/java/org/imgoing/api/controller/PlanController.java
> +        planService.deleteTask(plan);
응 나도 이부분 로직에 대해서 고민 했었는데 수정이 필요할 것 같네 일단 이렇게 해두고 로직 다시수정할게 ㅜㅜ

2021-10-23 06:57 UTC, ujin2021 commented on src/main/java/org/imgoing/api/controller/PlanController.java
> +    public ImgoingResponse<PlanDto> update (User user, @RequestBody @Valid PlanDto planDto) {
응응 이 부분 어디에 둘까 고민 했었는데 트랜잭션 문제도 그렇고 서비스로 옮기는게 맞는거 같아!

2021-10-23 06:58 UTC, ujin2021 commented on src/main/java/org/imgoing/api/controller/PlanController.java
> +        }
응응 그렇게 하는게 나은 것 같아 수정할게!

2021-10-23 08:37 UTC, ybell1028 commented on src/main/java/org/imgoing/api/domain/entity/Plan.java
> +}
@bluayer 인스턴스 값들이 언제 어디서 변해야 하는지 명확하기 구분할 수가 없다는 치명적인 단점이 있어서 setter를 안쓰는게 좋긴하지!
이전 프로젝트에서도 안쓰려고 했는데 테스트코드 짤 때 환경설정하려 보니까 setter가 필요해서 일단 넣어놓긴 했어
그럼 setter 없이 Builder 패턴만 쓰는게 더 좋을까?

2021-10-23 08:44 UTC, bluayer commented on src/main/java/org/imgoing/api/domain/entity/Plan.java
> +}
사실 User 같은 건 따로 setter 없이도 생성자 레벨에서 추가될 수 있다고 생각하고,
만약 데이터를 변경하게 하는 로직이 들어간 함수라면 set으로 시작하는 함수명보다는 도메인적으로 더 의미를 전할 수 있는 함수명을 써야 한다고 생각해 :)

2021-10-23 09:25 UTC, ybell1028 commented on src/main/java/org/imgoing/api/domain/entity/Plan.java
> +}
그럼 setter는 없애고 유진이가 한 것처럼 add* 메서드로 만들어야겠다!

2021-10-23 09:29 UTC, ujin2021 commented on src/main/java/org/imgoing/api/domain/entity/Plan.java
> +    @OneToMany(mappedBy = "plan", cascade = CascadeType.REMOVE, fetch = FetchType.EAGER)
수정했습니당

2021-10-23 10:43 UTC, ujin2021 commented on src/main/java/org/imgoing/api/controller/PlanController.java
> +        plantaskService.saveAll(plan.getPlantasks());
동의해요 좀더 생각해서 컨트롤러/서비스 분리를 해야겠어

2021-10-25 13:27 UTC, ujin2021 commented
plan udpate로직은 차차 수정하겠습니다!ㅜㅜ

2021-10-25 14:22 UTC, ybell1028 commented on src/main/java/org/imgoing/api/service/PlanService.java
> +    public List<Task> findNotBookmarkedTask (List<TaskDto> taskDtos) {
Mapper를 통해 Entity List를 생성해주는 메소드니까 createTasksNotBookmarked 같은 이름이 더 어울리지 않을까?

2021-10-25 14:23 UTC, ybell1028 commented on src/main/java/org/imgoing/api/service/PlanService.java
> +        plan.registerPlantask(tasks);
registerPlantask -> registerPlantask's' 속성 이름처럼 복수형으로 통일하자!

2021-10-25 14:25 UTC, ybell1028 approved these changes
자잘한 메소드명 외에는 딱히 변경할게 없는거 같아서 Approve 할께!

2021-10-26 01:57 UTC, bluayer approved these changes
좀 고쳐야 할 부분들이 보이긴 하지만, 일단 기한이 촉박하니깐 Approve!

2021-10-26 01:58 UTC, merged