Routine, Task 기능에 Validation 추가
depromeet/imgoing-backend pull request #44
Opened 2021-10-26 20:27 UTC by ybell1028

## 각 Dto Request와 Response로 분리

- Request 모델 변경에 따라 **Routine, Task 수정이 엔드포인트 id 지정 방식으로 변경**
- Dto도 불변으로 생성하기 위해 Setter를 삭제하고 Mapper가 Builder를 사용하게끔 설정 변경
- 역할을 명확하게 나타내도록 메서드, 변수명 변경

## Validation Message 관리 파일 추가

- resource bundle 이용
- properties 파일에 등록한 메세지를 Validation 어노테이션 속성 `message = "{task.notBlank.name}"`으로 사용 가능

## 루틴 생성 메서드 구조 변경

- 기존 코드는 Routine과 Routinetask 생성이 각각 이루어져서 Routinetask 생성 중 예외가 발생해도 Routine은 생성되는 이슈가 있었음
- Transaction의 이점을 살리기 위해 구조를 변경함

## etc.

- Task User 간 N:1 관계 설정, 관련 로직 추가

2021-10-27 08:11 UTC, bluayer requested changes
service 간에 의존성이 느는게 조금 걱정이긴 한데,
그 부분은 우리끼리 합의해야 할 꺼 같기도 해서 일단 그 부분은 터치 안 하는걸로!
궁금한 점 + 고려할 만한 점 남겼어!

2021-10-27 08:11 UTC, bluayer commented on src/main/java/org/imgoing/api/config/WebMvcConfig.java
> +        LocalValidatorFactoryBean validatorFactoryBean = new LocalValidatorFactoryBean();
이렇게 생성하면  LocalValidatorFactoryBean이 스프링 컨테이너에 등록되나..?

2021-10-27 08:11 UTC, bluayer commented on src/main/java/org/imgoing/api/service/PlanService.java
> +        List<TaskResponse> taskDtos = planSaveRequest.getTask();
Request에서 Response 리스트를 가져오는게 논리적으로 맞나?
나였으면 시스템에서 계속 사용되는 내용이라면 VO 같은 걸로 분리할 거 같긴 한데
이건 개인의 선호와 판단에 따라 갈릴 수 있는 부분이라서 한 번 고려만 해줘!

2021-10-27 08:11 UTC, bluayer commented on src/main/java/org/imgoing/api/config/WebMvcConfig.java
> +        messageSource.setBasename("classpath:/messages/validation");
이건 그냥 개인적으로 궁금한건데, 
validation 관련 메시지를 파일에서 로드하는 이유가 있어?

Reason Of Question : 메시지를 enum이나 클래스로 관리하면 compile 시점에서 그냥 처리되고 끝날텐데, 이렇게 하면 spring container 부팅 이후 라이프 사이클에서 처리할 때 파일로부터 데이터를 읽어오게 될꺼 같은데 이게 더 부하가 크지 않을까? 싶어져서!

2021-10-27 08:34 UTC, ybell1028 commented on src/main/java/org/imgoing/api/config/WebMvcConfig.java
> +        messageSource.setBasename("classpath:/messages/validation");
보통 ResourceBundle 사용해서 메시지를 처리하는건 로케일을 통한 국제화를 지원할 때 많이 쓰는 방법 같더라구
다른 레포지토리에 있는 코드 보고 추가한거라 성능에 관한 이슈는 생각을 안했네
우리 서비스가 아직 외국인 사용자 까지 생각할 정도는 아니니까 그냥 enum을 사용하는 걸로 할께

2021-10-27 08:35 UTC, ybell1028 commented on src/main/java/org/imgoing/api/service/PlanService.java
> +        List<TaskResponse> taskDtos = planSaveRequest.getTask();
나도 이 부분에 대해서 고민 많이 했는데 VO를 따로 만드는게 더 적절하겠다 조언 고마워!

2021-10-27 08:59 UTC, ybell1028 commented on src/main/java/org/imgoing/api/config/WebMvcConfig.java
> +        messageSource.setBasename("classpath:/messages/validation");
흠 생각해보니까 Exception 메시지처럼 자주 쓰이는 것도 아니고 애매하네
그냥 당분간은 어노테이션에 하드코딩 해놓는게 더 좋을듯!

2021-10-27 10:37 UTC, ybell1028 commented on src/main/java/org/imgoing/api/service/PlanService.java
> +        List<TaskResponse> taskDtos = planSaveRequest.getTask();
외부와 데이터 통신을 하는 객체는 Dto가 더 적절한 거 같아서 결국 원점으로 회귀해버렸다...

2021-10-27 11:20 UTC, ujin2021 commented on src/main/java/org/imgoing/api/mapper/TaskMapper.java
> +    Task responseToEntity(TaskDto taskDto);
responseToEntity가 어떤걸 뜻하는거야??

2021-10-27 11:21 UTC, ujin2021 approved these changes
코드 많이 수정했네 고생했엉!>!

2021-10-27 12:41 UTC, ybell1028 commented on src/main/java/org/imgoing/api/mapper/TaskMapper.java
> +    Task responseToEntity(TaskDto taskDto);
헉 이걸 깜빡하고 안고쳤네 가까운 시일내에 수정할께~

2021-10-28 08:38 UTC, bluayer approved these changes
LGTM 👍

2021-10-28 16:08 UTC, merged