Feat: 중요일정 등록/삭제/조회 기능, Interceptor 추가
depromeet/imgoing-backend pull request #54
Opened 2021-11-09 04:48 UTC by ujin2021

* 중요일정 등록/삭제 API
* 중요일정 조회 API
* Plan Interceptor 추가

2021-11-09 06:13 UTC, ybell1028 requested changes
전달사항 적용 감사감사~ 리뷰 내용 참고해서 조금만 더 고쳐줘!

2021-11-09 06:13 UTC, ybell1028 commented on src/main/java/org/imgoing/api/controller/PlanController.java
> +    public ImgoingResponse<ImportantPlanDto> registerImportant(
중요 일정은 isImportant = true인 일정이니까,
일정 생성, 수정 뷰에서 체크 박스 같은 것으로 지정할 텐데 생성, 수정 API를 사용하면 되지 않을까?
따로 새로운 컨트롤러를 만들 필요가 있을지 모르겠어

2021-11-09 06:13 UTC, ybell1028 commented on src/main/java/org/imgoing/api/service/PlanService.java
>          Plan newPlan = planMapper.toEntity(planRequest);
[이 포스팅](https://kafcamus.tistory.com/12)과  [이 포스팅](https://techblog.woowahan.com/2711/)은 Controller에서 Service로 넘어갈 때 값을 어떻게 넘겨주어야 할지 고민한 글이야
공통적으로 제시하고 있는 논점은 **특정 Dto에 Controller와 Service가 종속되어있으면 위험하니** 
1. 컨트롤러-서비스 통신 간에 사용하는 Dto를 따로 만들어주자
2. 범용적으로 사용하는 RequestDto를 서비스 메서드에 맞는 전용 Dto로 변경하여 사용하자

라는 솔루션을 제시하고 있어 
우리가 만든 Entity를 패러미터로 받고 Entity를 반환해주는 방식도 나쁘지 않은데, 이 경우 mapstruct 인터페이스가 중개자 역할을 대신하고 있는거라고 생각해

[이 포스팅](https://umbum.dev/1066)을 보면 MVC 구조에 대해 각 레이어 별로 어떻게 구분하면 좋을지 생각하는 글이야.
나도 Controller는 Presentation layer에 속한다고 생각해서 Entity <-> Dto 변환은 Controller에서 해주는게 더 타당하고 느끼는데 어떻게 생각해?

2021-11-09 06:13 UTC, ybell1028 commented on src/main/java/org/imgoing/api/service/PlanService.java
> +        deleteTask(modifiedPlan);
북마크가 아닌 task만 삭제하는 거라면 좀 더 명확한 네이밍이 필요할꺼 같아

2021-11-09 06:13 UTC, ybell1028 commented on src/main/java/org/imgoing/api/controller/PlanController.java
> +    @GetMapping("/bookmark")
중요 속성 이름처럼 엔드포인트도 바꾸자!

2021-11-09 08:10 UTC, ujin2021 commented on src/main/java/org/imgoing/api/controller/PlanController.java
> +    public ImgoingResponse<ImportantPlanDto> registerImportant(
![image](https://user-images.githubusercontent.com/53362054/140885956-2cd14d72-abaf-4a0a-bc26-f86c35fe6bef.png)

아직 페이지가 어떻게 나올지 확실하진 않은데, 저번주 수요일에 얘기한걸로는
일정 list가 뜨는 메인페이지에서 각 일정 왼쪽에 별표 아이콘 클릭/클릭해제 로 중요 일정 등록/해제 할 수 있도록 얘기가나와서! (이미지에서 star/unstar 버튼 처럼)
일정생성/수정 페이지엔 체크박스로 수정하는 폼은 포함안될거같아서 따로 api를 만들었엉

2021-11-09 08:13 UTC, ujin2021 commented on src/main/java/org/imgoing/api/controller/PlanController.java
> +    @GetMapping("/bookmark")
오 이걸 안바꿨었넹 오키오키!!

2021-11-09 08:51 UTC, ybell1028 commented on src/main/java/org/imgoing/api/controller/PlanController.java
> +    public ImgoingResponse<ImportantPlanDto> registerImportant(
일정이 작성자(user)에게만 보인다고 해도 보통 좋아요 비슷한 기능은 insert, update가 자주 일어나는 편이라
그대로 구현한다면 RDBMS의 성능 저하로 이어지기 때문에 Redis 같은 In-Memory DB를 사용하는 경우가 일반적인거 같아!

2021-11-09 09:21 UTC, ujin2021 commented on src/main/java/org/imgoing/api/service/PlanService.java
>          Plan newPlan = planMapper.toEntity(planRequest);
흠 planSerive의 modify method에서 
`List<TaskDto> taskDtos = planRequest.getTask();` 
이렇게 planRequest 에서 taskDto list를 가져와야 하는 코드가 들어가는데,
그럼 planService의 modify method의 파라미터를 (Plan oldPlan, Plan newPlan, TaskDto tasks) 로 넘기는게 나을까?

2021-11-09 11:06 UTC, ybell1028 commented on src/main/java/org/imgoing/api/service/PlanService.java
>          Plan newPlan = planMapper.toEntity(planRequest);
응 그게 더 좋을꺼같아
나도 루틴 수정 메소드를 `public Routine modify(Routine oldRoutine, Routine newRoutine, List<Long> updateTaskIdList)`로 작성해놨거든

2021-11-09 11:09 UTC, ujin2021 commented on src/main/java/org/imgoing/api/service/PlanService.java
>          Plan newPlan = planMapper.toEntity(planRequest);
오홍 알았어!! 고마워

2021-11-09 15:02 UTC, ybell1028 commented on src/main/java/org/imgoing/api/controller/PlanController.java
> +        Plan newPlan = planMapper.toEntityForSave(user, planSaveRequest);
이전에 리뷰 남겼던 것처럼 mapper도 Controller로 넘겨줬으면 좋겠네!
나도 처음엔 toEntityForSave 같은 메소드명을 썼는데 OOP의 다형성을 고려해서 패러미터 종류에 따라 오버로딩 해주고 있어

2021-11-12 06:24 UTC, bluayer requested changes
종훈이 형 review 반영하자!
(그리고 prepersist 아마 안 써도 될텐데, 그건 나중에 봅시당)

2021-11-13 11:50 UTC, ujin2021 commented on src/main/java/org/imgoing/api/controller/PlanController.java
> +        Plan newPlan = planMapper.toEntityForSave(user, planSaveRequest);
task는 bookmark 삭제하면서 mapper도 builder로 고쳐볼게! toEntityForSave는 이름 수정했어용

2021-11-14 23:50 UTC, ybell1028 approved these changes
고생 많았어!

2021-11-15 22:42 UTC, bluayer approved these changes

2021-11-15 22:42 UTC, merged