유저 관련 History 추가 & 지각 체크 및 유저 스탯 조회
depromeet/imgoing-backend pull request #61
Opened 2021-12-05 11:41 UTC by bluayer

# Summary 
- 유저 Plan, Plantask 조회 추가(해당 내용은 N days로 조회할 수 있도록 함)
- 도착 정보 기록, 지각 여부 저장
- User의 Monthly stat 조회 가능(도착까지 완료된 Plan 수, 지각한 Plan 수)

# 발견된 이상한 점
HttpServletRequet로 엔티티 조회해오면
트랜잭션이 끝나고, **영속성 컨텍스트가 준영속(detached) 상태로 바뀌면서**
dirty checking과 같은 이점을 못 누리게 되었는데,
***update 부분들은 나머지 컨트롤러에서 잘 처리된 것인지?***
(본 PR에서는 한 번 더 조회해오는 방식으로 처리함)

2021-12-06 03:21 UTC, ybell1028 requested changes
Interceptor에서 벗어나면 영속성 컨텍스트 풀려서 더티체킹 불가능한 문제는 확인해보고 수정해볼께!

2021-12-06 03:21 UTC, ybell1028 commented on Imgoing-api/src/main/java/org/imgoing/api/controller/PlantaskController.java
> +        List<PlantaskDto.Read> planTaskHistory = this.planService.getPlanHistoryDaysAgo(user, days).stream()
처음 Dto 구성할때 inner class를 사용했는데 @ApiModel 추가하지 않으면 Swagger가 제대로 인식하지 못하는 이슈 + extends로 모델별 코드 가독성이 떨어져서 요청 객체 Request랑 Dto(Vo)로 구분해서 클래스를 따로 만들어 쓰는게 좋을꺼같아
Routine이랑 Task 참조 바래~

2021-12-06 03:21 UTC, ybell1028 commented on Imgoing-api/src/main/java/org/imgoing/api/service/UserService.java
> +        System.out.println(startOfMonth);
logger로 고치거나 이제 쓰지 않는다면 지워주자

2021-12-07 00:48 UTC, ybell1028 approved these changes

2021-12-08 07:08 UTC, bluayer commented on Imgoing-api/src/main/java/org/imgoing/api/controller/PlantaskController.java
> +        List<PlantaskDto.Read> planTaskHistory = this.planService.getPlanHistoryDaysAgo(user, days).stream()
수정 완료

2021-12-08 07:08 UTC, merged